name: Deploy Simple Messaging App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env file
        uses: echo "PORT=${{ secrets.PORT }}"
      - name: Login to docker hub
        uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker build . -t khoerulih/simple-messaging-app:latest
      - name: Push docker image to docker hub
        uses: docker push khoerulih/simple-messaging-app:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull khoerulih/simple-messaging-app:latest
      - name: Delete old docker container
        run: docker rm -f simple-messaging-app
      - name: Running new docker container
        run: docker run -d -p 8080:8080 -p 4000:4000 --name simple-messaging-app khoerulih/simple-messaging-app:latest